preprocessing overhaul
Add DARTEL (spm12) realign & unwarp, normalization with std template,
all in parallel. Create separate topup step to create fieldmap before
preprocessing. Rewrite run_prep for transparency and functionality
with new DARTEL and topup scripts. No more need for step.par or
separate write_pfile function. Update matlab pfiles to use globals.m

diff --git a/scripts/preprocess/sbatch_prep_FSL b/scripts/preprocess/sbatch_prep_FSL
--- a/scripts/preprocess/sbatch_prep_FSL
+++ b/scripts/preprocess/sbatch_prep_FSL
@@ -76,10 +76,12 @@ if [[ $@ =~ -h|--help|-help ]]; then help_func; exit; fi
 while getopts "p:i:o:l:" opt; do
   case $opt in
     p)
-      pfile=${PARS_DIR}/$(basename $OPTARG)
-      if [ ! -f $pfile ]; then
+      pfile=$OPTARG
+      if [ ! -f $(full_file "${pfile}" "${SCRIPTS_DIR_PREP}") ]; then
         echo "$label ERROR: pfile $pfile does not exist."
         exit 1
+      else
+        pfile=$(full_file "${pfile}" "${SCRIPTS_DIR_PREP}")
       fi
       echo "$label Using pfile: $pfile"
       ;;
@@ -103,15 +105,14 @@ while getopts "p:i:o:l:" opt; do
       ;;
     l)
       flogfile=$OPTARG
-      logdir=$(dirname $flogfile)
-      if ! $(isDIR $logdir); then
-        echo "$label ERROR: $logdir is not a directory."
+      if [[ ! -d $(full_dir $(dirname ${flogfile})) ]]; then
+        echo "${label} ERROR: log directory $(dirname ${flogfile}) does not exist."
         exit 1
+      else 
+        logfile="$(full_dir $(dirname ${flogfile}))/$(basename ${flogfile})" 
       fi
-      logdir=$(full_dir $logdir)
-      flogfile=${logdir}/$(basename $flogfile)
-      touch $flogfile
-      echo "$label Using logfile: $flogfile instead of default" | tee -a $flogfile
+      touch $logfile
+      echo "$label Using logfile: $logfile instead of default" | tee -a $logfile
       ;;
     \?)
       echo "$label ERROR: unknown flag specified: ${opt}. Use -h for help."
@@ -127,17 +128,10 @@ done
 shift $((OPTIND -1))
 
 ############################## MAIN BODY OF SCRIPT #############################
-# extract the wd and wd/sdir folder location from the pfile by grabbing the quoted section
-# of the line that starts with "p.prepdir /whitespace/ = " and ends before ";"
-# wd_dir=$(grep -oP 'p.prepdir\s*=\s\K'.*?'(?=;)' ${pfile} | tr -d \')
-# # get task name based on wd_dir
-# tsk_dir=$(dirname $wd_dir)
-# tsk=${tsk_dir: -3}
-
-module load fsl
+module load fsl/5.0.9
 
 # source the pfile
-source ${PARS_DIR}/$(basename $pfile)
+source ${pfile}
 tsk=$TASK
 
 # if input_dir doesn't exist, use default from pfile
@@ -152,9 +146,6 @@ tsk=$TASK
 get_subs $input_dir $output_dir "$@"
 run_subs=( "${SUBS[@]}" )
 
-# extract prefix list from parameters file by finding the string between 3 uppercase letters and .m
-steps=$(echo "${pfile}" | grep -Po '.*\_[A-Z][A-Z][A-Z]\K.*?(?=.m)')
-
 # cycle through subjects 
 for subid in "${run_subs[@]}"; do 
 
@@ -164,24 +155,29 @@ for subid in "${run_subs[@]}"; do
   anat_brain=${fsl_prep}/anat_brain.nii.gz
   std_anat=${fsl_prep}/std_anat
   
-  if [[ -z $flogfile ]]; then logfile="${fsl_prep}/fsl_log.txt"; 
-  else logfile=$flogfile; fi
+  if [[ -z $logfile ]]; then 
+    logfile="${fsl_prep}/fsl_log.txt"
+    if [ ! -f ${logfile} ]; then touch ${logfile}; fi
+  else logfile=$logfile 
+  fi
 
   echo "${label} $(date) Beginning FSL preprocessing analysis of subject ${subid} \
 with pfile ${pfile}" | tee -a "${logfile}"
 
-  # Prepare anatmoical for normalization, if necessary
+  # Prepare anatomical for normalization, if necessary
   if [[ $NORM == 1 ]]; then
     if [[ ! -f $anat ]]; then 
-    echo "$label $(date) Anatomical $anat not found in $fsl_prep" | tee -a "$logfile" 
-    exit 1; fi
+      echo "$label $(date) Anatomical $anat not found in $fsl_prep" | tee -a "$logfile" 
+      exit 1
+    fi
     echo "$label $(date) Preparing anatomical for normalization." | tee -a "$logfile"
     #Skull strip (remove excess neck tissue first)
     standard_space_roi $anat "$std_anat"
     bet "$std_anat" $anat_brain $anat_bet_flag
     #Linear registration of anat_brain to MNI template
     echo "$label $(date) Registering anatomical to MNI space." | tee -a "$logfile"
-    flirt -ref "$fsl_template" -in "$anat_brain" -omat anat_affine_transf.mat -o "${anat_base}2MNI"
+    flirt -ref "$fsl_template" -in "$anat_brain" -omat anat_affine_transf.mat \
+       -o "${anat_base}2MNI"
     #Non-linear registration of anat_brain to template
     fnirt --in=$anat_brain --aff=anat_affine_transf.mat --cout=anat_nonlinear_transf \
            --config=T1_2_MNI152_2mm --iout=nonlinear_anat2MNI
@@ -197,24 +193,16 @@ with pfile ${pfile}" | tee -a "${logfile}"
     smooth_file="${fsl_prep}/s${epi_name}"
     normalize_file="${fsl_prep}/w${epi_name}"
     filter_file="${fsl_prep}/f${epi_name}"
-    SE_AP="${fsl_prep}/${tsk}_SE_AP.nii*"
-    topup_dir="${PREP_DIR}/topup/${subid}"
-    if [ ! -f $SE_AP ]; then 
-    	SE_AP="$(dirname $SE_AP)/ALL_SE_AP.nii*" 
-    	topup_dir=${PREP_DIR}/topup/${subid}
-    fi
-    mkdir -p $topup_dir
-    SE_PA="${SE_AP%AP.nii*}PA.nii*"
-    if [ ! -f ${logfile} ]; then touch ${logfile}; fi
+    # Get the TR from json file, or from fsl if that doesn't work
+    TR=$(read_json_value 'RepetitionTime' "${epi_name%.nii*}.json") || \
+        TR=$( fslval "${epi}" "pixdim4" )
+
     
     if [[ $SLICETIME == 1 ]]; then
       echo "$label $(date) Running slice timing $epi" | tee -a "$logfile"
-      slicetimer -i "$epi" -o "$time_file" --odd
+      slicetimer -i "$epi" -o "$time_file" --odd -r ${TR}
       cp $time_file $epi
       echo "${label} $(date) Ran slicetimer on $epi" | tee -a "$logfile"
-#    else 
-#      cp $epi $time_file
-#      echo "$(date) skipped slicetimer and copied raw as $time_file." >> "$logfile"
     fi
     
     if [[ $MOTION == 1 ]]; then
@@ -222,45 +210,16 @@ with pfile ${pfile}" | tee -a "${logfile}"
       mcflirt -in $epi -refvol $SE_AP -o $motion_file -mats -plots
       cp $motion_file $epi
       echo "${label} $(date) Ran motion correction on $epi" | tee -a "$logfile"
-#     else
- #      cp $epi $time_file
-  #     echo "$(date) skipped mcflirt and copied $time_file as $motion_file." >> "$logfile"
     fi
-    
 
     if [[ $UNWARP == 1 ]]; then
-      
-      if [ ! -f ${topup_dir}/topup_logout ]; then
-      echo "$label $(date) Starting topup." | tee -a "$logfile"
-      fslmerge -t ${topup_dir}/all_SE_epi ${SE_AP} ${SE_PA}
-      declare -a APinfo=($(fslinfo ${SE_AP})) #make array out of header info for AP epi to use in readout time calculation
-      declare -a PAinfo=($(fslinfo ${SE_PA}))
-      echo 'Generating acqparams file' | tee -a "$logfile"
-      if [ -e "${topup_dir}/acqparams.txt" ]; then rm -f 'acqparams.txt'; fi
-      readout=(${APinfo[3]}/${EPI_ACCEL}-1)*$EPI_ECHOSPACING
-      readout=$(echo "$readout" | bc -l)
-      for i in $(eval echo "{1..${APinfo[9]}}") ; do
-         cat >> ${topup_dir}/acqparams_epi.txt <<EOF
-0 -1 0 $readout
-EOF
-      done
-      for i in $(eval echo "{1..${APinfo[9]}}"); do
-        cat >> ${topup_dir}/acqparams_epi.txt <<EOF
-0 1 0 $readout
-EOF
-      done
-      echo '$label $(date) Running topup' | tee -a "$logfile"
-      topup --imain="${topup_dir}/all_SE_epi" --datain=${topup_dir}/acqparams_epi.txt --config=b02b0.cnf --out=${topup_dir}/topup_output --iout=${topup_dir}/topup_iout --fout=${topup_dir}/topup_fout --logout=${topup_dir}/topup_logout
-      fi
-      
+      echo -e "${label} WARNING: this script needs an update. Use DARTEL instead."
       echo "$label $(date) Applying topup" | tee -a "$logfile"
       outfile=$unwarp_file
-      applytopup --imain="$epi" --datain="${topup_dir}/acqparams_epi.txt" --inindex=1 --topup="${topup_dir}/topup_output" --method=jac -o "${outfile%.nii.gz}"
+      applytopup --imain="$epi" --datain="${topup_dir}/acqparams_epi.txt" --inindex=1 \
+        --topup="${topup_dir}/topup_output" --method=jac -o "${outfile%.nii.gz}"
       cp $unwarp_file $epi
       echo "${label} $(date) Ran topup to unwarp $unwarp_file" | tee -a "$logfile"
-  #  else
-  #    cp $motion_file $unwarp_file
-  #    echo "$(date) Skipped topup. Copied $motion_file to $unwarp_file" >> "$logfile"
     fi
     
     if [[ $NORM == 1 ]]; then
@@ -271,7 +230,8 @@ EOF
       bet ${epi} "${epi%.nii*}_brain" $epi_bet_flag
      echo "$label $(date) Registering ${epi} to structural.." | tee -a $logfile
     # 2. register epi to structural
-      epi_reg --epi="${epi%.nii*}_brain" --t1=$anat --t1brain=$anat_brain --out="${epi%.nii*}_brain2struct"      
+      epi_reg --epi="${epi%.nii*}_brain" --t1=$anat --t1brain=$anat_brain \
+        --out="${epi%.nii*}_brain2struct"      
     # 3. apply struct2MNI nonlinear warp
      echo "$label $(date) Registering ${epi} to MNI space.." | tee -a $logfile
       applywarp --ref="$fsl_template" --in="${epi%.nii*}_brain" --warp=anat_nonlinear_transf --premat="${epi%.nii*}_brain2struct.mat" --out="$normalize_file"
@@ -295,8 +255,8 @@ EOF
       # set default hp and lp
       hp=-1
       lp=-1
-      # get number of TRs in this run
-      TR=$( fslval "${epi}" "pixdim4" )
+      # get length of TR in this run
+      #TR=$( fslval "${epi}" "pixdim4" )
       # high pass filter
       if [[ $hFilter -ne -1 ]]; then
           hp=$(echo "${hFilter}/(${TR}*2)" | bc -l )
@@ -311,7 +271,8 @@ EOF
       fslmaths "${epi}" -bptf "${hp}" "${lp}" -add "${tempMean_file}" "${filter_file}"
       rm "${tempMean_file}.nii.gz"
       cp $filter_file $epi
-      echo "${label} $(date) Filtered ${epi} with high pass sigma $hp and low pass sigma $lp" | tee -a "$logfile"
+      echo "${label} $(date) Filtered ${epi} with high pass sigma $hp and low pass sigma $lp" \
+        | tee -a "$logfile"
     fi
   done
 done
