update convert_check with style standards and flags (untested)

diff --git a/scripts/utils/convert_check b/scripts/utils/convert_check
--- a/scripts/utils/convert_check
+++ b/scripts/utils/convert_check
@@ -1,56 +1,143 @@
 #!/bin/env bash
+# convert_check
+# 2016: Judith Mildner, jmildner@princeton.edu
+# Update 04/22/2017: JM
 #
-#Author: Judith Mildner
+# convert_check goes through subid_list.txt inside auxil/archive. For each subject
+# in the list, it checks for 1) no existing raw dir, 2) a dicom archive, 3) a run
+# order file. If these conditions are met, the script will launch convert_data
+# for the subject. Finally, it launches finish_convert, which will 'finish' the
+# log file when all subjects are done (used by funcs: wait_for_it)
+###############################################################################----------
+# files sourced:
+#  globals.par
+#  ${PROJECT_DIR}/auxil/archive/subid_list.txt
 #
-# This script checks which subjects need to be converted and calls the scripts
-# to convert them if necessary
-#
-#
-###############################################################################
-
+# flags:
+#  [-l <filename>] : full path to log file
+#                    default: ${PROJECT_DIR}/auxil/archive/LOG_convert.txt
+#  [-d <job ID>]   : sbatch dependency for convert_data jobs
+###############################################################################----------
 set -e
 
-source globals.par
-SUBID_LIST=${PROJECT_DIR}/arch/subid_list.txt
+function help_func () {
+cat <<- END
+convert_check [-lh]
+Description:
+------------
+  convert_check goes through subid_list.txt inside auxil/archive. For each subject
+  in the list, it checks for 1) no existing raw dir, 2) a dicom archive, 3) a run
+  order file. If these conditions are met, the script will launch convert_data
+  for the subject. Finally, it launches finish_convert, which will 'finish' the
+  log file when all subjects are done (used by funcs: wait_for_it)
+Usage:
+------
+  [-h | --help | -help]
+    Display this help
+  [-l <filename>]
+    Override the default log file location with a different filename (full path).
+    Default: ${PROJECT_DIR}/auxil/archive/LOG_convert.txt
+  [-d <job ID>]
+    sbatch dependency for convert_data jobs
+END
+}
+#First, check for help flag (multi-character flags not supported by getopts)
+if [[ $@ =~ --help|-help ]]; then help_func; exit; fi
+
+#Get the name of the directory this script is in, to create full path to globals.par
+script_dir="$( cd "$(dirname "$0")" ; pwd -P )"
+#Assuming the scripts dir is somewhere in the full path, this finds globals.par
+source "${script_dir%scripts/*}/scripts/globals.par"
+#Load subid_list
+SUBID_LIST=${PROJECT_DIR}/auxil/archive/subid_list.txt
+
+#logfile variables (flag can overwrite filename initialized here)
 label="[CONVERT]"
-[[ -z $1 ]] && logfile=${ROJECT_DIR}/arch/LOG_convert.txt || logfile=$1
+logfile=${PROJECT_DIR}/arch/LOG_convert.txt
 
-echo $logfile
-rm $logfile
-
-echo
-
-exec 9<> $SUBID_LIST #open file descriptor for subid_list.txt file -JNM
-while read -r -u 9 full_subj subj imgtype; do  #read in lines from subid_list, assign them to variables, and loop through subid_list
-  echo "${label}" | tee -a $logfile
-  if [[ $imgtype != 'dicom' ]]; then #test if imagetype in subid_list is dicom. Could support other types in the future
-    echo "${label} No dicom data available for subject $full_subj" | tee -a $logfile
-    continue;
-  fi
-  if [[ $full_subj = '' ]]; then continue; fi
-  output_prefix=$subj
-  # set necessary variables and check if prerequisites exist. -JNM
-  dicom_archive="${PROJECT_DIR}/arch/dicom/raw_${full_subj}.tar.gz"
-  if [[ ! -f $dicom_archive ]]; then echo "${label} ${dicom_archive} does not exist. Skipping $full_subj." | tee -a $logfile; continue; fi
-  output_dir="${PROJECT_DIR}/raw/"
-  if [[ -n $(find $output_dir -name $subj) ]]; then echo "${label} $subj already converted. Skipping $full_subj" | tee -a $logfile; continue; fi
-  run_order_file="${PROJECT_DIR}/arch/subpars/runorders/${full_subj}.txt"
-  if [[ ! -f $run_order_file ]]; then echo "${label} ${run_order_file} does not exist. Skipping $full_subj." | tee -a $logfile; continue; fi
-  job_id=$(sbatch -t 60 convert_data $subj $full_subj | grep -o '[0-9]*')
-  jobs+=":$job_id"
+#Parse flags other than help
+while getopts ":l:d:h" opt; do
+  case $opt in
+    l)
+      logfile=$OPTARG
+      if [ ! -d $(dirname $logfile)]; then
+        echo "[CONVERT] ERROR: $logfile directory does not exist."
+        exit
+      fi
+      touch $logfile
+      echo "[CONVERT] Using logfile: $logfile instead of default" | tee -a $logfile
+      ;;
+    d)
+      init_dependency=$OPTARG
+      #check if this is a number
+      if ! [[ $init_dependency =~ '^[0-9]+$' ]]; then
+        echo "[CONVERT] dependency job number $init_dependency is not a number."
+        exit
+      fi
+      echo "[CONVERT] Using initial dependency $init_dependency" | tee -a $logfile
+      ;;
+    h)
+      help_func
+      exit
+      ;;
+    \?)
+      echo "[CONVERT] ERROR: unknown flag specified: "
+      ;;
+    esac
 done
 
+exec 9<> $SUBID_LIST #open file descriptor for subid_list.txt file -JNM
+#read in lines from subid_list, assign them to variables, and loop through subid_list
+  while read -r -u 9 full_subj subj imgtype; do
+    echo "${label}" | tee -a $logfile
+    #test if imagetype in subid_list is dicom. Could support other types in the future
+    if [[ $imgtype != 'dicom' ]]; then
+      echo "${label} No dicom data available for subject $full_subj" | tee -a $logfile
+      continue;
+    fi
+    if [[ $full_subj = '' ]]; then continue; fi
+    output_prefix=$subj
+
+    #1) check if raw directory does not exist
+    output_dir="${PROJECT_DIR}/raw/"
+    if [[ -n $(find $output_dir -name $subj) ]]; then
+      echo "${label} $subj already converted. Skipping $full_subj" \
+        | tee -a $logfile
+      continue
+    fi
+
+    #2) check if dicom archive exists
+    dicom_archive="${PROJECT_DIR}/arch/dicom/raw_${full_subj}.tar.gz"
+    if [[ ! -f $dicom_archive ]]; then
+      echo "${label} ${dicom_archive} does not exist. Skipping $full_subj." \
+        | tee -a $logfile
+      continue
+    fi
+
+    #3) check if run order file exists
+    run_order_file="${PROJECT_DIR}/arch/subpars/runorders/${full_subj}.txt"
+    if [[ ! -f $run_order_file ]]; then
+    echo "${label} ${run_order_file} does not exist. Skipping $full_subj." \
+      | tee -a $logfile;
+    continue
+    fi
+    init_dep_flag="--dependency=afterok:$init_dependency"
+    #If all 3 criteria are passed, convert this subject's data
+    job_id=$(sbatch $init_dep_flag -t 60 convert_data $subj $full_subj | grep -o '[0-9]*')
+    jobs+=":$job_id"
+  done
+
+# Create dependency for finish jobs
 unset dependency_flag
 jobs=${jobs#:}
-[[ ! -z "$jobs" ]] && dependency_flag="--dependency=afterok:$jobs"
-
+# if no convert jobs were started, finish depends on initial dependency
+if [[ -z "$jobs" ]]; then
+  dependency_flag="--dependency=afterok:$init_dependency"
+# if convert jobs were started, finish depends on these
+else
+   dependency_flag="--dependency=afterok:$jobs"
+fi
+# Run the finish_convert job
 sbatch -t 1 -J finish_convert -p all $dependency_flag finish_log ${label} ${logfile}
 
-
-
-
-
-exec 9>&- #close subid_list.txt. file -JNM   
-
-
-
+exec 9>&- #close subid_list.txt. file -JNM
