sub_level glm: update help, input, con list output

diff --git a/scripts/sub_level/glm/run_glm_SPM12W b/scripts/sub_level/glm/run_glm_SPM12W
--- a/scripts/sub_level/glm/run_glm_SPM12W
+++ b/scripts/sub_level/glm/run_glm_SPM12W
@@ -43,7 +43,7 @@ source ${SCRIPT_DIR_UTIL}/funcs
 ######################### SET UP & PARSE ARGUMENTS #############################
 function help_func () {
 cat << END
-  sbatch_SPM12w_prep [-lh] -p <pfile> [-i <input_dir>] [-o <output_dir>] [-l <logfile>] [-d <jobIDs>
+  run_glm_SPM12w [-lh] -p <pfile> [-i <input_dir>] [-o <output_dir>] [-l <logfile>] [-d <jobIDs>]
   Description:
   ------------
 	Launches preprocessing in matlab using SPM12w based on specified parameters in pfile
@@ -140,33 +140,21 @@ while getopts "p:i:o:l:d:" opt; do
     esac
 done
 [[ -z $pfile ]] && echo "$label ERROR: -p flag required. Use -h for help." && exit 1
-[[ -z ${input_dir} ]] && echo "$label ERROR: -i flag required. Use -h for help." && exit 1
-[[ -z ${output_dir} ]] && echo "$label ERROR: -o flag required. Use -h for help." && exit 1
+if [[ -z ${input_dir} ]]; then 
+  glm_task=$(get_matlab_var 'tsk' "${pfile}")
+  glm_wd=$(get_matlab_var 'wd' "${pfile}")
+  input_dir="${PREP_DIR}/${glm_task}/${glm_wd}"
+  [[ ! -d ${input_dir} ]] && echo "${label} ERROR: ${input_dir} not found" && exit 1
+fi
+if [[ -z ${output_dir} ]]; then 
+  glm_output=$(get_matlab_var 'glm.glm_name' "${pfile}")
+  output_dir="${ANALYSIS_DIR}/${USER}/glm/${glm_output}"
+  mkdir -p "${output_dir}"
+fi
 #remove used input args
 shift $((OPTIND -1))
 
 ############################## MAIN BODY OF SCRIPT #############################
-# # extract the wd and wd/sdir folder location from the pfile by grabbing the quoted section
-# # of the line that starts with "p.prepdir /whitespace/ = " and ends before ";"
-# wd_name=$(grep -oP 'wd\s*=\s\K'.*?'(?=;)' ${pfile} | tr -d \')
-# TSK=$(grep -oP 'tsk\s*=\s\K'.*?'(?=;)' ${pfile} | tr -d \')
-# wd_dir=${PREP_DIR}/${TSK}/${wd_name}
-
-# # extract the glm folder location from the pfile by grabbing the quoted section of the line that starts with "glm.glm_name /whitespace/ = " and ends before ";"
-# glm_name=$(grep -oP 'glm.glm_name\s*=\s\K'.*?'(?=;)' ${pfile} | tr -d \')
-# username=$(grep -oP 'glm.username\s*=\s\K'.*?'(?=;)' ${pfile} | tr -d \')
-# d=${PROJECT_DIR}/analysis/${username}
-# ! $(isDIR $d) && mkdir $d
-# glm_basedir=${d}/glm
-# ! $(isDIR $glm_basedir) && mkdir $glm_basedir
-# glm_dir=${glm_basedir}/${glm_name}
-# ! $(isDIR $glm_dir) && mkdir $glm_dir
-
-# # if input_dir doesn't exist, use default from pfile
-# [[ -z ${input_dir} ]] && input_dir=${wd_dir}
-# # if output_dir doesn't exist, use default from pfile
-# [[ -z ${output_dir} ]] && output_dir=${glm_dir}
-# if logfile doesn't exist, use default from pfile
 logfile_name=LOG_glm.txt
 [[ -z $flogfile ]] && logfile=${output_dir}/${logfile_name}
 
