group_level/glm: find pfile

diff --git a/scripts/group_level/glm/run_rfx_SPM12W b/scripts/group_level/glm/run_rfx_SPM12W
--- a/scripts/group_level/glm/run_rfx_SPM12W
+++ b/scripts/group_level/glm/run_rfx_SPM12W
@@ -78,51 +78,54 @@ if [[ $@ =~ -h|--help|-help ]]; then help_func; exit; fi
 while getopts "p:i:o:l:d:" opt; do
   case ${opt} in
     p)
-      pfile=$(full_file "${OPTARG}" "${SCRIPT_DIR_GRPLVL}")
-      if [ ! -f ${pfile} ]; then
-        sub_pfile=$(full_file "${OPTARG}" "${SCRIPT_DIR_SUBLVL}")
-        if [ ! -f ${sub_pfile} ]; then
-          echo "$label ERROR: pfile $pfile does not exist."
-          exit 1
-        else
-          pfile="${sub_pfile}"
+      pfilename="${OPTARG}"
+      pfile=$(full_file "${pfilename}" "${SCRIPT_DIR_GRPLVL}")
+      if [[ ! -f ${pfile} ]]; then
+        sub_pfile=$(full_file "${pfilename}" "${SCRIPT_DIR_SUBLVL}")
+        if [[ ! -f ${sub_pfile} ]]; then
+          sub_pfile=$(full_file "${pfilename}" "${SCRIPT_DIR_SUBLVL}/glm")
+          if [[ ! -f ${sub_pfile} ]]; then
+            echo "${label} ERROR: pfile ${pfile} does not exist."
+            exit 1
+          fi
         fi
+        pfile="${sub_pfile}"
       fi
-      echo "$label Using pfile: $pfile"
+      echo "${label} Using pfile: ${pfile}"
       ;;
     i)
-          input_dir=${PREP_DIR}/$OPTARG
-      if ! $(isDIR ${input_dir}); then
-        echo "$label ERROR: input directory $input_dir is not a directory."
+      input_dir="${PREP_DIR}/${OPTARG}"
+      if [[ $(isDIR ${input_dir}) != true ]]; then
+        echo "${label} ERROR: input directory ${input_dir} is not a directory."
         exit 1
       fi
       input_dir=$(full_dir ${input_dir})
-      echo "$label input_dir: $input_dir"
+      echo "${label} input_dir: ${input_dir}"
       ;;
     o)
-          output_dir=${PROJECT_DIR}/analysis/${USER}/glm/$OPTARG
-          mkdir -p ${output_dir}
+      output_dir="${PROJECT_DIR}/analysis/${USER}/glm/${OPTARG}"
+      mkdir -p ${output_dir}
       # if ! $(isDIR ${output_dir}); then
       #   echo "$label ERROR: output directory $output_dir is not a directory."
       #   exit 1
       # fi
       # output_dir=$(full_dir $output_dir)
-      echo "$label output_dir: $output_dir"
+      echo "${label} output_dir: ${output_dir}"
       ;;
     l)
-      flogfile=$OPTARG
+      flogfile=${OPTARG}
       logdir=$(dirname ${flogfile})
       if ! $(isDIR ${logdir}); then
-        echo "$label ERROR: $logdir is not a directory."
+        echo "${label} ERROR: ${logdir} is not a directory."
         exit 1
       fi
       logdir=$(full_dir ${logdir})
-      flogfile=${logdir}/$(basename ${flogfile})
-      touch ${flogfile}
-      echo "$label Using logfile: $flogfile instead of default" | tee -a ${flogfile}
+      flogfile="${logdir}/$(basename ${flogfile})"
+      touch "${flogfile}"
+      echo "${label} Using logfile: ${flogfile} instead of default" | tee -a ${flogfile}
       ;;
     d)
-      jobIDs=$OPTARG
+      jobIDs=${OPTARG}
       if [[ ${jobIDs:0:1} == d ]]; then
         dependency_flag=${jobIDs:16}
       elif [[ ${jobIDs:0:2} == '--' ]]; then
@@ -132,20 +135,20 @@ while getopts "p:i:o:l:d:" opt; do
       elif $(isNUM ${jobIDs:0}); then
         dependency_flag='--dependency=afterok:'${jobIDs}
       else
-        echo "${label} ERROR: $jobIDs is not a valid dependency arg. Use -h for help."
+        echo "${label} ERROR: ${jobIDs} is not a valid dependency arg. Use -h for help."
         exit 1
       fi
       ;;
     \?)
-      echo "$label ERROR: unknown flag specified: ${opt}. Use -h for help."
+      echo "${label} ERROR: unknown flag specified: ${opt}. Use -h for help."
       exit 1
       ;;
     : ) #Catch options without arguments
-      echo "$label ERROR: -$OPTARG requires an argument. Use -h for help."
+      echo "${label} ERROR: -${OPTARG} requires an argument. Use -h for help."
       exit 1
     esac
 done
-[[ -z ${pfile} ]] && echo "$label ERROR: -p flag required. Use -h for help." && exit 1
+[[ -z ${pfile} ]] && echo "${label} ERROR: -p flag required. Use -h for help." && exit 1
 if [[ -z ${input_dir} ]]; then 
   glm_task=$(get_matlab_var 'tsk' "${pfile}")
   glm_wd=$(get_matlab_var 'wd' "${pfile}")
