minor style fixes

diff --git a/scripts/group_level/glm/run_rfx_SPM12W b/scripts/group_level/glm/run_rfx_SPM12W
--- a/scripts/group_level/glm/run_rfx_SPM12W
+++ b/scripts/group_level/glm/run_rfx_SPM12W
@@ -1,6 +1,6 @@
-#!/bin/env bash
+#!/usr/bin/env bash
 # 
-# jmildner@princeton.edu, 20 Sep 2017
+# September 20, 2017: Judith Mildner (jmildner@)
 #
 # Run second level glm using SPM12W (they call it rfx). You can use the same pfile as
 # in your first level glm. Currently, SPM12W only supports one sample t test. One-way
@@ -76,10 +76,10 @@ if [[ $@ =~ -h|--help|-help ]]; then help_func; exit; fi
 
 #Parse flags other than help
 while getopts "p:i:o:l:d:" opt; do
-  case $opt in
+  case ${opt} in
     p)
       pfile=$(full_file "${OPTARG}" "${SCRIPT_DIR_GRPLVL}")
-      if [ ! -f $pfile ]; then
+      if [ ! -f ${pfile} ]; then
         sub_pfile=$(full_file "${OPTARG}" "${SCRIPT_DIR_SUBLVL}")
         if [ ! -f ${sub_pfile} ]; then
           echo "$label ERROR: pfile $pfile does not exist."
@@ -96,12 +96,12 @@ while getopts "p:i:o:l:d:" opt; do
         echo "$label ERROR: input directory $input_dir is not a directory."
         exit 1
       fi
-      input_dir=$(full_dir $input_dir)
+      input_dir=$(full_dir ${input_dir})
       echo "$label input_dir: $input_dir"
       ;;
     o)
           output_dir=${PROJECT_DIR}/analysis/${USER}/glm/$OPTARG
-          mkdir -p $output_dir
+          mkdir -p ${output_dir}
       # if ! $(isDIR ${output_dir}); then
       #   echo "$label ERROR: output directory $output_dir is not a directory."
       #   exit 1
@@ -111,26 +111,26 @@ while getopts "p:i:o:l:d:" opt; do
       ;;
     l)
       flogfile=$OPTARG
-      logdir=$(dirname $flogfile)
-      if ! $(isDIR $logdir); then
+      logdir=$(dirname ${flogfile})
+      if ! $(isDIR ${logdir}); then
         echo "$label ERROR: $logdir is not a directory."
         exit 1
       fi
-      logdir=$(full_dir $logdir)
-      flogfile=${logdir}/$(basename $flogfile)
-      touch $flogfile
-      echo "$label Using logfile: $flogfile instead of default" | tee -a $flogfile
+      logdir=$(full_dir ${logdir})
+      flogfile=${logdir}/$(basename ${flogfile})
+      touch ${flogfile}
+      echo "$label Using logfile: $flogfile instead of default" | tee -a ${flogfile}
       ;;
     d)
       jobIDs=$OPTARG
       if [[ ${jobIDs:0:1} == d ]]; then
         dependency_flag=${jobIDs:16}
       elif [[ ${jobIDs:0:2} == '--' ]]; then
-        dependency_flag=$jobIDs
+        dependency_flag=${jobIDs}
       elif [[ ${jobIDs:0:5} == after ]]; then
-        dependency_flag='--dependency='$jobIDs
+        dependency_flag='--dependency='${jobIDs}
       elif $(isNUM ${jobIDs:0}); then
-        dependency_flag='--dependency=afterok:'$jobIDs
+        dependency_flag='--dependency=afterok:'${jobIDs}
       else
         echo "${label} ERROR: $jobIDs is not a valid dependency arg. Use -h for help."
         exit 1
@@ -145,7 +145,7 @@ while getopts "p:i:o:l:d:" opt; do
       exit 1
     esac
 done
-[[ -z $pfile ]] && echo "$label ERROR: -p flag required. Use -h for help." && exit 1
+[[ -z ${pfile} ]] && echo "$label ERROR: -p flag required. Use -h for help." && exit 1
 if [[ -z ${input_dir} ]]; then 
   glm_task=$(get_matlab_var 'tsk' "${pfile}")
   glm_wd=$(get_matlab_var 'wd' "${pfile}")
@@ -161,30 +161,31 @@ shift $((OPTIND -1))
 
 ############################## MAIN BODY OF SCRIPT #############################
 logfile_name=LOG_rfx.txt
-[[ -z $flogfile ]] && logfile=${output_dir}/${logfile_name}
+[[ -z ${flogfile} ]] && logfile="${output_dir}/${logfile_name}"
 
-pfile_name=$(basename $pfile)
-DATE=`date +%Y%m%d`
-cp ${pfile} ${output_dir}/${DATE}_${pfile_name}
+pfile_name=$(basename ${pfile})
+DATE=$(date +%Y%m%d)
+cp "${pfile}" "${output_dir}/${DATE}_${pfile_name}"
 
 #check if there are remaining arguments, that have not yet been processed
 # if so, get subject IDs by calling get_subs
 if [[ -n "${@}" ]]; then
-  get_subs $input_dir $output_dir "$@"
+  get_subs ${input_dir} ${output_dir} "$@"
   run_subs=( "${SUBS[@]}" )
 fi
 
 unset all_jobs
 
-echo "${label} Beginning level 2 GLM analysis of ${run_subs[@]} for $TSK with pfile $pfile" | tee -a $logfile
+echo "${label} Beginning level 2 GLM analysis of ${run_subs[@]} for $TSK with pfile ${pfile}" \
+  | tee -a ${logfile}
 
 jobname=glm_lvl2
-flags="-o ${OUT_DIR}/${jobname}-%j.out --mail-user=$USER_EMAIL -J ${jobname} ${dependency_flag}"
-prev_jobid=$(sbatch $flags sbatch_rfx_SPM12W -p $pfile ${run_subs[@]} | grep -o '[0-9]*')
+flags="-o ${OUT_DIR}/${jobname}-%j.out --mail-user=${USER_EMAIL} -J ${jobname} ${dependency_flag}"
+prev_jobid=$(sbatch ${flags} sbatch_rfx_SPM12W -p ${pfile} ${run_subs[@]} | grep -o '[0-9]*')
 all_jobs+=":${prev_jobid}"
     
-echo "${label} ${jobname} job ${prev_jobid} submitted for level 2 GLM  with pfile $pfile" \
-   | tee -a ${logfile_sub} $logfile
+echo "${label} ${jobname} job ${prev_jobid} submitted for level 2 GLM  with pfile ${pfile}" \
+   | tee -a ${logfile_sub} ${logfile}
 echo ${label}
 
 echo "${label} dependency_flag=--dependency=afterok${all_jobs}"
diff --git a/scripts/preprocess/sbatch_prep_FSL b/scripts/preprocess/sbatch_prep_FSL
--- a/scripts/preprocess/sbatch_prep_FSL
+++ b/scripts/preprocess/sbatch_prep_FSL
@@ -43,7 +43,7 @@ d="$(dirname -- "$(pwd)")"
 # source globals.par
 source "${d%scripts*}/scripts/globals.par"
 # source functions
-source ${SCRIPT_DIR_UTIL}/funcs
+source "${SCRIPT_DIR_UTIL}/funcs"
 
 ######################### SET UP & PARSE ARGUMENTS #############################
 function help_func () {
@@ -74,56 +74,56 @@ if [[ $@ =~ -h|--help|-help ]]; then help_func; exit; fi
 
 #Parse flags other than help
 while getopts "p:i:o:l:" opt; do
-  case $opt in
+  case ${opt} in
     p)
-      pfile=$OPTARG
-      if [ ! -f $(full_file "${pfile}" "${SCRIPTS_DIR_PREP}") ]; then
-        echo "$label ERROR: pfile $pfile does not exist."
+      pfile=${OPTARG}
+      if [ ! -f $(full_file "${pfile}" "${SCRIPT_DIR_PREP}") ]; then
+        echo "${label} ERROR: pfile ${pfile} does not exist."
         exit 1
       else
-        pfile=$(full_file "${pfile}" "${SCRIPTS_DIR_PREP}")
+        pfile=$(full_file "${pfile}" "${SCRIPT_DIR_PREP}")
       fi
-      echo "$label Using pfile: $pfile"
+      echo "${label} Using pfile: ${pfile}"
       ;;
     i)
-    input_dir=$OPTARG
+    input_dir=${OPTARG}
       if ! $(isDIR ${input_dir}); then
-        echo "$label ERROR: input directory $input_dir is not a directory."
+        echo "${label} ERROR: input directory ${input_dir} is not a directory."
         exit 1
       fi
-      input_dir=$(full_dir $input_dir)
-      echo "$label input_dir: $input_dir"
+      input_dir=$(full_dir ${input_dir})
+      echo "${label} input_dir: ${input_dir}"
       ;;
     o)
-    output_dir=$OPTARG
+    output_dir=${OPTARG}
       if ! $(isDIR ${output_dir}); then
-        echo "$label ERROR: output directory $output_dir is not a directory."
+        echo "${label} ERROR: output directory ${output_dir} is not a directory."
         exit 1
       fi
-      output_dir=$(full_dir $output_dir)
-      echo "$label output_dir: $output_dir"
+      output_dir=$(full_dir ${output_dir})
+      echo "${label} output_dir: ${output_dir}"
       ;;
     l)
-      flogfile=$OPTARG
+      flogfile=${OPTARG}
       if [[ ! -d $(full_dir $(dirname ${flogfile})) ]]; then
         echo "${label} ERROR: log directory $(dirname ${flogfile}) does not exist."
         exit 1
       else 
         logfile="$(full_dir $(dirname ${flogfile}))/$(basename ${flogfile})" 
       fi
-      touch $logfile
-      echo "$label Using logfile: $logfile instead of default" | tee -a $logfile
+      touch "${logfile}"
+      echo "${label} Using logfile: ${logfile} instead of default" | tee -a "${logfile}"
       ;;
     \?)
-      echo "$label ERROR: unknown flag specified: ${opt}. Use -h for help."
+      echo "${label} ERROR: unknown flag specified: ${opt}. Use -h for help."
       exit 1
       ;;
     : ) #Catch options without arguments
-      echo "$label ERROR: -$OPTARG requires an argument. Use -h for help."
+      echo "${label} ERROR: -${OPTARG} requires an argument. Use -h for help."
       exit 1
     esac
 done
-[[ -z $pfile ]] && echo "$label ERROR: -p flag required. Use -h for help." && exit 1
+[[ -z ${pfile} ]] && echo "${label} ERROR: -p flag required. Use -h for help." && exit 1
 #remove used input args
 shift $((OPTIND -1))
 
@@ -131,62 +131,62 @@ shift $((OPTIND -1))
 module load fsl/5.0.9
 
 # source the pfile
-source ${pfile}
-tsk=$TASK
+source "${pfile}"
+tsk="${TASK}"
 
 # if input_dir doesn't exist, use default from pfile
-[[ -z ${input_dir} ]] && input_dir=${RAW_DIR}/${tsk}/
+[[ -z ${input_dir} ]] && input_dir="${RAW_DIR}/${tsk}/"
 # if output_dir doesn't exist, use default from pfile
-[[ -z ${output_dir} ]] && output_dir=$PREP
+[[ -z ${output_dir} ]] && output_dir="${PREP}"
 # if logfile doesn't exist, use default from pfile
-[[ -z $flogfile ]] && logdir=${output_dir}
+[[ -z ${flogfile} ]] && logdir="${output_dir}"
 
 #check if there are remaining arguments, that have not yet been processed
 # if so, get subject IDs by calling get_subs
-get_subs $input_dir $output_dir "$@"
+get_subs "${input_dir}" "${output_dir}" "$@"
 run_subs=( "${SUBS[@]}" )
 
 # cycle through subjects 
 for subid in "${run_subs[@]}"; do 
 
-  fsl_prep=${PREP}/${subid}
-  anat=${fsl_prep}/anat.nii.gz
-  anat_base=${fsl_prep}/anat
-  anat_brain=${fsl_prep}/anat_brain.nii.gz
-  std_anat=${fsl_prep}/std_anat
+  fsl_prep="${PREP}/${subid}"
+  anat="${fsl_prep}/anat.nii.gz"
+  anat_base="${fsl_prep}/anat"
+  anat_brain="${fsl_prep}/anat_brain.nii.gz"
+  std_anat="${fsl_prep}/std_anat"
   
-  if [[ -z $logfile ]]; then 
+  if [[ -z ${logfile} ]]; then
     logfile="${fsl_prep}/fsl_log.txt"
-    if [ ! -f ${logfile} ]; then touch ${logfile}; fi
-  else logfile=$logfile 
+    if [ ! -f ${logfile} ]; then touch "${logfile}"; fi
+  else logfile="${logfile}"
   fi
 
   echo "${label} $(date) Beginning FSL preprocessing analysis of subject ${subid} \
 with pfile ${pfile}" | tee -a "${logfile}"
 
   # Prepare anatomical for normalization, if necessary
-  if [[ $NORM == 1 ]]; then
-    if [[ ! -f $anat ]]; then 
-      echo "$label $(date) Anatomical $anat not found in $fsl_prep" | tee -a "$logfile" 
+  if [[ ${NORM} == 1 ]]; then
+    if [[ ! -f ${anat} ]]; then
+      echo "${label} $(date) Anatomical $anat not found in $fsl_prep" | tee -a "${logfile}"
       exit 1
     fi
-    echo "$label $(date) Preparing anatomical for normalization." | tee -a "$logfile"
+    echo "${label} $(date) Preparing anatomical for normalization." | tee -a "${logfile}"
     #Skull strip (remove excess neck tissue first)
-    standard_space_roi $anat "$std_anat"
-    bet "$std_anat" $anat_brain $anat_bet_flag
+    standard_space_roi ${anat} "$std_anat"
+    bet "$std_anat" ${anat_brain} ${anat_bet_flag}
     #Linear registration of anat_brain to MNI template
-    echo "$label $(date) Registering anatomical to MNI space." | tee -a "$logfile"
+    echo "${label} $(date) Registering anatomical to MNI space." | tee -a "${logfile}"
     flirt -ref "$fsl_template" -in "$anat_brain" -omat anat_affine_transf.mat \
        -o "${anat_base}2MNI"
     #Non-linear registration of anat_brain to template
-    fnirt --in=$anat_brain --aff=anat_affine_transf.mat --cout=anat_nonlinear_transf \
+    fnirt --in=${anat_brain} --aff=anat_affine_transf.mat --cout=anat_nonlinear_transf \
            --config=T1_2_MNI152_2mm --iout=nonlinear_anat2MNI
-    echo "$label $(date) Prepared anatomical for normalization." | tee -a "$logfile"
+    echo "${label} $(date) Prepared anatomical for normalization." | tee -a "${logfile}"
   fi
 
   for epi in ${fsl_prep}/epi_r*.nii*; do
     #set local variables for this subject and task.
-    epi_name="$(basename $epi)"
+    epi_name="$(basename ${epi})"
     time_file="${fsl_prep}/a${epi_name}"
     motion_file="${fsl_prep}/r${epi_name}"
     unwarp_file="${fsl_prep}/u${epi_name}"
@@ -198,84 +198,86 @@ with pfile ${pfile}" | tee -a "${logfile}"
         TR=$( fslval "${epi}" "pixdim4" )
 
     
-    if [[ $SLICETIME == 1 ]]; then
-      echo "$label $(date) Running slice timing $epi" | tee -a "$logfile"
+    if [[ ${SLICETIME} == 1 ]]; then
+      echo "${label} $(date) Running slice timing $epi" | tee -a "${logfile}"
       slicetimer -i "$epi" -o "$time_file" --odd -r ${TR}
-      cp $time_file $epi
-      echo "${label} $(date) Ran slicetimer on $epi" | tee -a "$logfile"
+      cp ${time_file} ${epi}
+      echo "${label} $(date) Ran slicetimer on $epi" | tee -a "${logfile}"
     fi
     
-    if [[ $MOTION == 1 ]]; then
-      echo "$label $(date) Running motion correction on $epi." | tee -a "$logfile"
-      mcflirt -in $epi -refvol $SE_AP -o $motion_file -mats -plots
-      cp $motion_file $epi
-      echo "${label} $(date) Ran motion correction on $epi" | tee -a "$logfile"
+    if [[ ${MOTION} == 1 ]]; then
+      echo "${label} $(date) Running motion correction on $epi." | tee -a "${logfile}"
+      mcflirt -in ${epi} -refvol ${SE_AP} -o ${motion_file} -mats -plots
+      cp ${motion_file} ${epi}
+      echo "${label} $(date) Ran motion correction on $epi" | tee -a "${logfile}"
     fi
 
-    if [[ $UNWARP == 1 ]]; then
+    if [[ ${UNWARP} == 1 ]]; then
       echo -e "${label} WARNING: this script needs an update. Use DARTEL instead."
-      echo "$label $(date) Applying topup" | tee -a "$logfile"
-      outfile=$unwarp_file
+      echo "${label} $(date) Applying topup" | tee -a "${logfile}"
+      outfile=${unwarp_file}
       applytopup --imain="$epi" --datain="${topup_dir}/acqparams_epi.txt" --inindex=1 \
         --topup="${topup_dir}/topup_output" --method=jac -o "${outfile%.nii.gz}"
-      cp $unwarp_file $epi
-      echo "${label} $(date) Ran topup to unwarp $unwarp_file" | tee -a "$logfile"
+      cp ${unwarp_file} ${epi}
+      echo "${label} $(date) Ran topup to unwarp ${unwarp_file}" | tee -a "${logfile}"
     fi
     
-    if [[ $NORM == 1 ]]; then
+    if [[ ${NORM} == 1 ]]; then
     # Normalize to MNI space
      #requires anatomical
-     echo "$label $(date) Normalizing ${epi}.." | tee -a $logfile
+     echo "${label} $(date) Normalizing ${epi}.." | tee -a ${logfile}
     # 1. skull strip
-      bet ${epi} "${epi%.nii*}_brain" $epi_bet_flag
-     echo "$label $(date) Registering ${epi} to structural.." | tee -a $logfile
+      bet ${epi} "${epi%.nii*}_brain" "${epi_bet_flag}"
+     echo "${label} $(date) Registering ${epi} to structural.." | tee -a ${logfile}
     # 2. register epi to structural
-      epi_reg --epi="${epi%.nii*}_brain" --t1=$anat --t1brain=$anat_brain \
+      epi_reg --epi="${epi%.nii*}_brain" --t1=${anat} --t1brain=${anat_brain} \
         --out="${epi%.nii*}_brain2struct"      
     # 3. apply struct2MNI nonlinear warp
-     echo "$label $(date) Registering ${epi} to MNI space.." | tee -a $logfile
-      applywarp --ref="$fsl_template" --in="${epi%.nii*}_brain" --warp=anat_nonlinear_transf --premat="${epi%.nii*}_brain2struct.mat" --out="$normalize_file"
+     echo "${label} $(date) Registering ${epi} to MNI space.." | tee -a ${logfile}
+      applywarp --ref="${fsl_template}" --in="${epi%.nii*}_brain" \
+        --warp=anat_nonlinear_transf --premat="${epi%.nii*}_brain2struct.mat" \
+        --out="${normalize_file}"
     
-      cp $normalize_file $epi
-     echo "$label $(date) Normalized ${epi} to MNI space.." | tee -a $logfile
+      cp ${normalize_file} ${epi}
+     echo "${label} $(date) Normalized ${epi} to MNI space.." | tee -a ${logfile}
     
     fi
   #smoothing 
-    if [[ $FWHM != 0 ]]; then
-      echo "$label $(date) smoothing $epi with kernel $FWHM" | tee -a "$logfile"
+    if [[ ${FWHM} != 0 ]]; then
+      echo "${label} $(date) smoothing $epi with kernel ${FWHM}" | tee -a "${logfile}"
       sigma=`echo "2.35482004503*$FWHM" | bc -l` #calculate sigma value needed for FSL smoothing based on FWHM
-      fslmaths $epi -s $sigma $smooth_file
-      cp $smooth_file $epi
-      echo "${label} $(date) Ran smoothing with $FWHM FWHM" | tee -a "$logfile"
+      fslmaths ${epi} -s ${sigma} ${smooth_file}
+      cp ${smooth_file} ${epi}
+      echo "${label} $(date) Ran smoothing with ${FWHM} FWHM" | tee -a "${logfile}"
     fi
 
-    if [[ $FILTER == 1 ]]; then
+    if [[ ${FILTER} == 1 ]]; then
       # apply band pass filter
-      echo "$label $(date) bandpass filtering $epi"
+      echo "${label} $(date) bandpass filtering ${epi}"
       # set default hp and lp
       hp=-1
       lp=-1
       # get length of TR in this run
       #TR=$( fslval "${epi}" "pixdim4" )
       # high pass filter
-      if [[ $hFilter -ne -1 ]]; then
+      if [[ ${hFilter} -ne -1 ]]; then
           hp=$(echo "${hFilter}/(${TR}*2)" | bc -l )
           echo "high pass filter is ${hFilter} seconds, sigma ${hp}"
       fi
       # low pass filter
-      if [[ $lFilter -ne -1 ]]; then lp=$(echo "$lFilter/($TR*2)" | bc -l ); fi
+      if [[ ${lFilter} -ne -1 ]]; then lp=$(echo "$lFilter/($TR*2)" | bc -l ); fi
       # filter epi
       echo "using high pass sigma $hp, low pass sigma $lp"
       tempMean_file="${fsl_prep}/tempMean"
       fslmaths "${epi}" -Tmean "${tempMean_file}"
       fslmaths "${epi}" -bptf "${hp}" "${lp}" -add "${tempMean_file}" "${filter_file}"
       rm "${tempMean_file}.nii.gz"
-      cp $filter_file $epi
-      echo "${label} $(date) Filtered ${epi} with high pass sigma $hp and low pass sigma $lp" \
-        | tee -a "$logfile"
+      cp "${filter_file}" "${epi}"
+      echo "${label} $(date) Filtered ${epi} with high pass sigma ${hp} and low pass sigma ${lp}" \
+        | tee -a "${logfile}"
     fi
   done
 done
 
 # move current output file to output directory
-bash $SCRIPT_DIR_UTIL/cleanup_output $SLURM_JOB_ID
+bash "${SCRIPT_DIR_UTIL}/cleanup_output" "${SLURM_JOB_ID}"
diff --git a/scripts/preprocess/sbatch_prep_SPM12W b/scripts/preprocess/sbatch_prep_SPM12W
--- a/scripts/preprocess/sbatch_prep_SPM12W
+++ b/scripts/preprocess/sbatch_prep_SPM12W
@@ -35,7 +35,7 @@
 #SBATCH -p all									# DON'T CHANGE
 
 set -e
-echo "on host: `hostname` "
+echo "on host: $(hostname)"
 label='[SPM12W]'
 
 module load matlab/R2016b
@@ -46,7 +46,7 @@ d="$(dirname -- "$(pwd)")"
 # source globals.par
 source "${d%scripts*}/scripts/globals.par"
 # source functions
-source ${SCRIPT_DIR_UTIL}/funcs
+source "${SCRIPT_DIR_UTIL}/funcs"
 
 ######################### SET UP & PARSE ARGUMENTS #############################
 function help_func () {
@@ -77,55 +77,55 @@ if [[ $@ =~ -h|--help|-help ]]; then help_func; exit; fi
 
 #Parse flags other than help
 while getopts "p:i:o:l:" opt; do
-  case $opt in
+  case ${opt} in
     p)
-      pfile=${SCRIPT_DIR_PREP}/$(basename $OPTARG)
-      if [ ! -f $pfile ]; then
-        echo "$label ERROR: pfile $pfile does not exist."
+      pfile="${SCRIPT_DIR_PREP}/$(basename $OPTARG)"
+      if [ ! -f ${pfile} ]; then
+        echo "${label} ERROR: pfile ${pfile} does not exist."
         exit 1
       fi
-      echo "$label Using pfile: $pfile"
+      echo "${label} Using pfile: ${pfile}"
       ;;
     i)
 	  input_dir=$OPTARG
       if ! $(isDIR ${input_dir}); then
-        echo "$label ERROR: input directory $input_dir is not a directory."
+        echo "${label} ERROR: input directory ${input_dir} is not a directory."
         exit 1
       fi
-      input_dir=$(full_dir $input_dir)
-      echo "$label input_dir: $input_dir"
+      input_dir=$(full_dir ${input_dir})
+      echo "${label} input_dir: ${input_dir}"
       ;;
     o)
 	  output_dir=$OPTARG
       if ! $(isDIR ${output_dir}); then
-        echo "$label ERROR: output directory $output_dir is not a directory."
+        echo "${label} ERROR: output directory ${output_dir} is not a directory."
         exit 1
       fi
-      output_dir=$(full_dir $output_dir)
-      echo "$label output_dir: $output_dir"
+      output_dir=$(full_dir ${output_dir})
+      echo "${label} output_dir: ${output_dir}"
       ;;
     l)
       flogfile=$OPTARG
-      logdir=$(dirname $flogfile)
-      if ! $(isDIR $logdir); then
-        echo "$label ERROR: $logdir is not a directory."
+      logdir=$(dirname ${flogfile})
+      if ! $(isDIR ${logdir}); then
+        echo "${label} ERROR: ${logdir} is not a directory."
         exit 1
       fi
-      logdir=$(full_dir $logdir)
-      flogfile=${logdir}/$(basename $flogfile)
-      touch $flogfile
-      echo "$label Using logfile: $flogfile instead of default" | tee -a $flogfile
+      logdir=$(full_dir ${logdir})
+      flogfile="${logdir}/$(basename ${flogfile})"
+      touch ${flogfile}
+      echo "${label} Using logfile: ${flogfile} instead of default" | tee -a ${flogfile}
       ;;
     \?)
-      echo "$label ERROR: unknown flag specified: ${opt}. Use -h for help."
+      echo "${label} ERROR: unknown flag specified: ${opt}. Use -h for help."
       exit 1
       ;;
     : ) #Catch options without arguments
-      echo "$label ERROR: -$OPTARG requires an argument. Use -h for help."
+      echo "${label} ERROR: -$OPTARG requires an argument. Use -h for help."
       exit 1
     esac
 done
-[[ -z $pfile ]] && echo "$label ERROR: -p flag required. Use -h for help." && exit 1
+[[ -z ${pfile} ]] && echo "${label} ERROR: -p flag required. Use -h for help." && exit 1
 #remove used input args
 shift $((OPTIND -1))
 
@@ -134,19 +134,19 @@ shift $((OPTIND -1))
 # of the line that starts with "p.prepdir /whitespace/ = " and ends before ";"
 wd_dir=$(grep -oP 'p.prepdir\s*=\s\K'.*?'(?=;)' ${pfile} | tr -d \')
 # get task name based on wd_dir
-tsk_dir=$(dirname $wd_dir)
-tsk=${tsk_dir: -3}
+tsk_dir=$(dirname ${wd_dir})
+tsk="${tsk_dir: -3}"
 
 # if input_dir doesn't exist, use default from pfile
-[[ -z ${input_dir} ]] && input_dir=${RAW_DIR}/$tsk/
+[[ -z ${input_dir} ]] && input_dir="${RAW_DIR}/${tsk}/"
 # if output_dir doesn't exist, use default from pfile
-[[ -z ${output_dir} ]] && output_dir=${wd_dir}
+[[ -z ${output_dir} ]] && output_dir="${wd_dir}"
 # if logfile doesn't exist, use default from pfile
-[[ -z $flogfile ]] && logdir=${wd_dir}
+[[ -z ${flogfile} ]] && logdir="${wd_dir}"
 
 #check if there are remaining arguments, that have not yet been processed
 # if so, get subject IDs by calling get_subs
-get_subs $input_dir $output_dir "$@"
+get_subs ${input_dir} ${output_dir} "$@"
 run_subs=( "${SUBS[@]}" )
 
 # extract prefix list from parameters file by finding the string between 3 uppercase letters and .m
@@ -154,8 +154,8 @@ steps=$(echo "${pfile}" | grep -Po '.*\_[A-Z][A-Z][A-Z]\K.*?(?=.m)')
 
 # cycle through subjects since SPM12w can't run more than one subject at a time
 for subid in "${run_subs[@]}"; do 
-	if [[ -z $flogfile ]]; then logfile=${logdir}/${subid}/LOG_spmw.txt; 
-	else logfile=$flogfile; fi
+	if [[ -z ${flogfile} ]]; then logfile="${logdir}/${subid}/LOG_spmw.txt";
+	else logfile="${flogfile}"; fi
 
 	echo "${label} $(date) Beginning SPM12w analysis of subject ${subid} with pfile \
 ${pfile}" | tee -a "${logfile}"
@@ -168,13 +168,13 @@ ${pfile}" | tee -a "${logfile}"
 	# if unwarp AND normalization are on, skip 'r' prefix (not written out if both of these steps are included)
   if [[ $(echo ${steps} | grep -o 'uw') ]]; then
           steps=$(echo ${steps} | sed 's/r//')
-          echo "${label} 'r' removed. steps=$steps"
+          echo "${label} 'r' removed. steps=${steps}"
         fi
 	# update epi_r##.nii* files to their most recent versions
-	update_nii ${wd_dir} ${steps} ${SUBIDS[@]}
+	update_nii "${wd_dir}" "${steps}" "${SUBIDS[@]}"
 
 	echo "${label} DONE. $(date)" | tee -a "${logfile}"
 done
 
 # move current output file to output directory
-bash $SCRIPT_DIR_UTIL/cleanup_output $SLURM_JOB_ID
+bash "${SCRIPT_DIR_UTIL}/cleanup_output" "${SLURM_JOB_ID}"
diff --git a/scripts/sub_level/glm/run_glm_SPM12W b/scripts/sub_level/glm/run_glm_SPM12W
--- a/scripts/sub_level/glm/run_glm_SPM12W
+++ b/scripts/sub_level/glm/run_glm_SPM12W
@@ -1,4 +1,4 @@
-#!/bin/env bash
+#!/usr/bin/env bash
 # 
 # May 8, 2017: Miriam Weaverdyck updated script to work with new filestructure/standards
 #
@@ -38,7 +38,7 @@ d="$(dirname -- "$(pwd)")"
 # source globals.par
 source "${d%scripts*}/scripts/globals.par"
 # source functions
-source ${SCRIPT_DIR_UTIL}/funcs
+source "${SCRIPT_DIR_UTIL}/funcs"
 
 ######################### SET UP & PARSE ARGUMENTS #############################
 function help_func () {
@@ -75,71 +75,71 @@ if [[ $@ =~ -h|--help|-help ]]; then help_func; exit; fi
 
 #Parse flags other than help
 while getopts "p:i:o:l:d:" opt; do
-  case $opt in
+  case ${opt} in
     p)
       pfile=${SCRIPT_DIR}/sub_level/glm/$(basename $OPTARG)
-      if [ ! -f $pfile ]; then
-        echo "$label ERROR: pfile $pfile does not exist."
+      if [ ! -f ${pfile} ]; then
+        echo "${label} ERROR: pfile ${pfile} does not exist."
         exit 1
       fi
-      echo "$label Using pfile: $pfile"
+      echo "${label} Using pfile: ${pfile}"
       ;;
     i)
           input_dir=${PREP_DIR}/$OPTARG
       if ! $(isDIR ${input_dir}); then
-        echo "$label ERROR: input directory $input_dir is not a directory."
+        echo "${label} ERROR: input directory ${input_dir} is not a directory."
         exit 1
       fi
-      input_dir=$(full_dir $input_dir)
-      echo "$label input_dir: $input_dir"
+      input_dir=$(full_dir ${input_dir})
+      echo "${label} input_dir: ${input_dir}"
       ;;
     o)
-          output_dir=${PROJECT_DIR}/analysis/${USER}/glm/$OPTARG
-          mkdir -p $output_dir
+          output_dir="${PROJECT_DIR}/analysis/${USER}/glm/$OPTARG"
+          mkdir -p "${output_dir}"
       # if ! $(isDIR ${output_dir}); then
-      #   echo "$label ERROR: output directory $output_dir is not a directory."
+      #   echo "${label} ERROR: output directory $output_dir is not a directory."
       #   exit 1
       # fi
       # output_dir=$(full_dir $output_dir)
-      echo "$label output_dir: $output_dir"
+      echo "${label} output_dir: ${output_dir}"
       ;;
     l)
       flogfile=$OPTARG
-      logdir=$(dirname $flogfile)
-      if ! $(isDIR $logdir); then
-        echo "$label ERROR: $logdir is not a directory."
+      logdir=$(dirname ${flogfile})
+      if ! $(isDIR ${logdir}); then
+        echo "${label} ERROR: ${logdir} is not a directory."
         exit 1
       fi
-      logdir=$(full_dir $logdir)
-      flogfile=${logdir}/$(basename $flogfile)
-      touch $flogfile
-      echo "$label Using logfile: $flogfile instead of default" | tee -a $flogfile
+      logdir=$(full_dir ${logdir})
+      flogfile=${logdir}/$(basename ${flogfile})
+      touch ${flogfile}
+      echo "${label} Using logfile: ${flogfile} instead of default" | tee -a ${flogfile}
       ;;
     d)
       jobIDs=$OPTARG
       if [[ ${jobIDs:0:1} == d ]]; then
         dependency_flag=${jobIDs:16}
       elif [[ ${jobIDs:0:2} == '--' ]]; then
-        dependency_flag=$jobIDs
+        dependency_flag=${jobIDs}
       elif [[ ${jobIDs:0:5} == after ]]; then
-        dependency_flag='--dependency='$jobIDs
+        dependency_flag='--dependency='${jobIDs}
       elif $(isNUM ${jobIDs:0}); then
-        dependency_flag='--dependency=afterok:'$jobIDs
+        dependency_flag='--dependency=afterok:'${jobIDs}
       else
-        echo "${label} ERROR: $jobIDs is not a valid dependency arg. Use -h for help."
+        echo "${label} ERROR: ${jobIDs} is not a valid dependency arg. Use -h for help."
         exit 1
       fi
       ;;
     \?)
-      echo "$label ERROR: unknown flag specified: ${opt}. Use -h for help."
+      echo "${label} ERROR: unknown flag specified: ${opt}. Use -h for help."
       exit 1
       ;;
     : ) #Catch options without arguments
-      echo "$label ERROR: -$OPTARG requires an argument. Use -h for help."
+      echo "${label} ERROR: -${OPTARG} requires an argument. Use -h for help."
       exit 1
     esac
 done
-[[ -z $pfile ]] && echo "$label ERROR: -p flag required. Use -h for help." && exit 1
+[[ -z ${pfile} ]] && echo "${label} ERROR: -p flag required. Use -h for help." && exit 1
 if [[ -z ${input_dir} ]]; then 
   glm_task=$(get_matlab_var 'tsk' "${pfile}")
   glm_wd=$(get_matlab_var 'wd' "${pfile}")
@@ -156,31 +156,31 @@ shift $((OPTIND -1))
 
 ############################## MAIN BODY OF SCRIPT #############################
 logfile_name=LOG_glm.txt
-[[ -z $flogfile ]] && logfile=${output_dir}/${logfile_name}
+[[ -z ${flogfile} ]] && logfile=${output_dir}/${logfile_name}
 
-pfile_name=$(basename $pfile)
+pfile_name=$(basename ${pfile})
 DATE=`date +%Y%m%d`
 cp ${pfile} ${output_dir}/${DATE}_${pfile_name}
 
 #check if there are remaining arguments, that have not yet been processed
 # if so, get subject IDs by calling get_subs
-get_subs $input_dir $output_dir "$@"
+get_subs ${input_dir} ${output_dir} "$@"
 run_subs=( "${SUBS[@]}" )
 
 unset all_jobs
 
 for sub in ${run_subs[@]}; do
-  echo "${label} Beginning level 1 GLM analysis of $sub for $TSK with pfile $pfile" | tee -a $logfile
-  subdir=${output_dir}/${sub}
+  echo "${label} Beginning level 1 GLM analysis of ${sub} for ${TSK} with pfile ${pfile}" | tee -a ${logfile}
+  subdir="${output_dir}/${sub}"
   mkdir -p ${subdir}
-  logfile_sub=${subdir}/${logfile_name}
+  logfile_sub="${subdir}/${logfile_name}"
 
-  jobname=glm_${sub}
+  jobname="glm_${sub}"
   flags="-o ${OUT_DIR}/${jobname}-%j.out --mail-user=$USER_EMAIL -J ${jobname} ${dependency_flag}"
-  prev_jobid=$(sbatch $flags sbatch_glm_SPM12W -p $pfile -l ${logfile_sub} $sub | grep -o '[0-9]*')
+  prev_jobid=$(sbatch ${flags} sbatch_glm_SPM12W -p ${pfile} -l ${logfile_sub} ${sub} | grep -o '[0-9]*')
   all_jobs+=":${prev_jobid}"
     
-  echo "${label} ${jobname} job ${prev_jobid} submitted for level 1 GLM for $subject with pfile $pfile" | tee -a ${logfile_sub} $logfile
+  echo "${label} ${jobname} job ${prev_jobid} submitted for level 1 GLM for $subject with pfile $pfile" | tee -a ${logfile_sub} ${logfile}
   echo ${label}
 done
 
diff --git a/scripts/sub_level/glm/sbatch_glm_SPM12W b/scripts/sub_level/glm/sbatch_glm_SPM12W
--- a/scripts/sub_level/glm/sbatch_glm_SPM12W
+++ b/scripts/sub_level/glm/sbatch_glm_SPM12W
@@ -1,4 +1,4 @@
-#!/bin/env bash
+#!/usr/bin/env bash
 #
 # May 8, 2017: Miriam Weaverdyck updated script to work with new filestructure and standards
 #
@@ -32,7 +32,7 @@
 #SBATCH -p all				# DON'T CHANGE
 
 set -e
-echo "on host: `hostname`"
+echo "on host: $(hostname)"
 label='[GLM]'
 
 ######################### SOURCE FILES ########################################
@@ -41,7 +41,7 @@ d="$(dirname -- "$(pwd)")"
 # source globals.par
 source "${d%scripts*}/scripts/globals.par"
 # source functions
-source ${SCRIPT_DIR_UTIL}/funcs
+source "${SCRIPT_DIR_UTIL}/funcs"
 
 ######################### SET UP & PARSE ARGUMENTS #############################
 function help_func () {
@@ -66,47 +66,47 @@ if [[ $@ =~ -h|--help|-help ]]; then help_func; exit; fi
 
 #Parse flags other than help
 while getopts "p:l:" opt; do
-  case $opt in
+  case ${opt} in
     p)
-      pfile=${SCRIPT_DIR}/sub_level/glm/$(basename $OPTARG)
-      if [ ! -f $pfile ]; then
-        echo "$label ERROR: pfile $pfile does not exist."
+      pfile="${SCRIPT_DIR}/sub_level/glm/$(basename ${OPTARG})"
+      if [ ! -f ${pfile} ]; then
+        echo "${label} ERROR: pfile ${pfile} does not exist."
         exit 1
       fi
-      echo "$label Using pfile: $pfile"
+      echo "${label} Using pfile: ${pfile}"
       ;;
     l)
-      flogfile=$OPTARG
-      logdir=$(dirname $flogfile)
-      if ! $(isDIR $logdir); then
-        echo "$label ERROR: $logdir is not a directory."
+      flogfile=${OPTARG}
+      logdir=$(dirname ${flogfile})
+      if ! $(isDIR ${logdir}); then
+        echo "${label} ERROR: ${logdir }is not a directory."
         exit 1
       fi
-      logdir=$(full_dir $logdir)
-      flogfile=${logdir}/$(basename $flogfile)
-      touch $flogfile
-      echo "$label Using logfile: $flogfile instead of default" | tee -a $flogfile
+      logdir=$(full_dir ${logdir})
+      flogfile=${logdir}/$(basename ${flogfile})
+      touch ${flogfile}
+      echo "${label} Using logfile: ${flogfile} instead of default" | tee -a ${flogfile}
       ;;
     \?)
-      echo "$label ERROR: unknown flag specified: ${opt}. Use -h for help."
+      echo "${label} ERROR: unknown flag specified: ${opt}. Use -h for help."
       exit 1
       ;;
     : ) #Catch options without arguments
-      echo "$label ERROR: -$OPTARG requires an argument. Use -h for help."
+      echo "${label} ERROR: -${OPTARG} requires an argument. Use -h for help."
       exit 1
     esac
 done
-[[ -z $pfile ]] && echo "$label ERROR: -p flag required. Use -h for help." && exit 1
+[[ -z ${pfile} ]] && echo "${label} ERROR: -p flag required. Use -h for help." && exit 1
 #remove used input args
 shift $((OPTIND -1))
 
 ############################## MAIN BODY OF SCRIPT #############################
 
-logfile=$flogfile
+logfile=${flogfile}
 subject=$1; shift
 
-num2subID $subject
-sub=$SUBIDS
+num2subID "${subject}"
+sub=${SUBIDS}
 
 module load matlab
 matlab -nosplash -nodisplay -nodesktop -r \
diff --git a/scripts/sub_level/roi/sbatch_rest_preglm_FSL b/scripts/sub_level/roi/sbatch_rest_preglm_FSL
--- a/scripts/sub_level/roi/sbatch_rest_preglm_FSL
+++ b/scripts/sub_level/roi/sbatch_rest_preglm_FSL
@@ -75,20 +75,20 @@ label='[GEN_REGR]'
 
 # Get globals
 #Check if PROJECT_DIR is already known
-if [[ ! -z $PROJECT_DIR ]]; then
-  source ${PROJECT_DIR}/scripts/globals.par
+if [[ ! -z ${PROJECT_DIR} ]]; then
+  source "${PROJECT_DIR}/scripts/globals.par"
 #check if globals is in the current directory
 elif [[ -f ./globals.par ]]; then
   source globals.par
 #Check if we're not inside a slurm job
-elif [[ -z $SLURM_JOB_ID ]]; then
+elif [[ -z ${SLURM_JOB_ID} ]]; then
   #Get the name of the directory this script is in, to create full path to globals.par
   script_dir="$( cd "${BASH_SOURCE%/*}" ; pwd -P )"
   #Assuming the scripts dir is somewhere in the full path, this finds globals.par
   source "${script_dir%scripts/*}/scripts/globals.par"
 #error out if we can't find globals with any of these strategies
 else
-  echo "$label ERROR: can't find globals.par. Please source globals.par before starting."
+  echo "${label} ERROR: can't find globals.par. Please source globals.par before starting."
   exit
 fi
 
@@ -96,7 +96,7 @@ source "${SCRIPT_DIR_UTIL}/funcs"
 
 # Parse input arguments
 while getopts ":p:dh" opt; do
-  case $opt in
+  case ${opt} in
     p)
       pfile=${OPTARG}
       if [[ -f ${SCRIPT_DIR_ROI}/${pfile} ]]; then
@@ -127,11 +127,11 @@ while getopts ":p:dh" opt; do
       exit
     ;;
     \?)
-    echo "$label ERROR: unknown flag specified: ${opt}. Use --help for help."
+    echo "${label} ERROR: unknown flag specified: ${opt}. Use --help for help."
     exit 1
     ;;
     : )
-    echo "$label ERROR: $OPTARG requires an argument. Use --help for help."
+    echo "${label} ERROR: ${OPTARG} requires an argument. Use --help for help."
     exit 1
     ;;
   esac
@@ -141,7 +141,7 @@ done
 shift $((OPTIND -1))
 #check if there are remaining arguments, that have not yet been processed
 if [[ -z $@ ]]; then
-  echo "$label ERROR: missing subject argument. Use -h for help"
+  echo "${label} ERROR: missing subject argument. Use -h for help"
   exit 1
 fi
 
@@ -175,13 +175,13 @@ cat <<- EOM | tee "${logfile}"
 EOM
 ################################################################################
 prep_dir="${prep_dir}/${subject}"
-for epi in $prep_dir/epi_r*.nii.gz; do
+for epi in ${prep_dir}/epi_r*.nii.gz; do
   #make sure it exists
-  [ -e $file ] || (echo "$label ERROR: $epi not found" | tee -a "${logfile}" && exit)
+  [ -e ${file} ] || (echo "${label} ERROR: ${epi} not found" | tee -a "${logfile}" && exit)
   #get just the epi name
-  epi=$(basename "$epi")
-  fslmaths "${prep_dir}/$epi" -nan "${tmp_rst_dir}/$epi"
-  nvols=$(fslnvols "${tmp_rst_dir}/$epi")
+  epi=$(basename "${epi}")
+  fslmaths "${prep_dir}/${epi}" -nan "${tmp_rst_dir}/${epi}"
+  nvols=$(fslnvols "${tmp_rst_dir}/${epi}")
   moco_dir="${tmp_rst_dir}/mc_${epi%.nii*}"
   #motion regressors: change from 1 file with 6 columns to 1 file per parameter
   if [ "${motion}" == 1 ]; then
@@ -205,7 +205,7 @@ for epi in $prep_dir/epi_r*.nii.gz; do
   #trim first n volumes from start of epi and motion parameters
   if [ "${trim}" != 0 ]; then
     echo "${label} trimming first ${trim} volumes from ${epi}" | tee -a "${logfile}"
-    new_nvols=$(( $nvols - $trim ))
+    new_nvols=$(( ${nvols} - ${trim} ))
     #trim volumes from beginning of epi
     fslroi "${tmp_rst_dir}/${epi}" "${tmp_rst_dir}/t${epi}" ${trim} ${new_nvols}
     #trim first volumes from motion parameter files as well
@@ -237,17 +237,17 @@ for epi in $prep_dir/epi_r*.nii.gz; do
 
   #bandpass filter
   if [[ "${bandpass}" == 1 ]]; then
-    echo "${label} bandpass filtering $epi" | tee -a "${logfile}"
+    echo "${label} bandpass filtering ${epi}" | tee -a "${logfile}"
     hp=-1
     lp=-1
     TR=$( read_json_value "RepetitionTime" "${prep_dir}/${epi%.nii*}.json" )
-    if [[ $hFilter != -1 ]]; then
+    if [[ ${hFilter} != -1 ]]; then
       hp=$(echo "${hFilter}/(${TR}*2)" | bc -l )
       echo "${label} high pass filter is ${hFilter} seconds, sigma ${hp}" \
         | tee -a "${logfile}"
     fi
-    if [[ $lFilter != -1 ]]; then
-      lp=$(echo "$lFilter/($TR*2)" | bc -l )
+    if [[ ${lFilter} != -1 ]]; then
+      lp=$(echo "${lFilter}/(${TR}*2)" | bc -l )
     fi
     #calculate the mean timecourse
     echo "${label} using high pass sigma ${hp}, low pass sigma ${lp}" \
