changing globals.sh->globals.par

diff --git a/notes/write_pfile_DARTEL b/notes/write_pfile_DARTEL
--- a/notes/write_pfile_DARTEL
+++ b/notes/write_pfile_DARTEL
@@ -4,9 +4,14 @@
 # this script writes out the parameters to the p_study.m file 
 # (a matlab file to be read by SPM12w)
 
-source pars.sh
-source study_info.sh
-source ../arch/globals.sh
+set -e # stop immediately when an error occurs
+source pars.par
+source ../arch/globals.par
+
+if [ $NORM != 'DARTEL' ]; then
+	echo "ABORTING: DARTEL was not chosen for normalization in /notes/pars.par."
+	exit 0
+fi
 
 SAVE_DIR=$PROJECT_DIR/$SCRIPT_DIR_SPM8
 
@@ -19,11 +24,13 @@ else
 	SMOOTHING=0
 fi
 
-# Check if $last_prep is empty. If so, assign it SPM by default
-if [ -z "$last_prep" ]; then 
-echo "WARNING: Variable 'last_prep' is unset.  Setting it to SPM as default."; SUB_DIR=prep/SPM*;
-else SUB_DIR=prep/$last_prep*;
+if [ $REALIGN == 'DARTEL' ]; then 
+	REALIGN=1;
+else 
+	REALIGN=0;
 fi
+
+SUB_DIR=prep/wd
 
 cat <<EOT > $SAVE_DIR/p_DARTEL.m
 % Parameters file for SPM8 DARTEL normalization
@@ -62,6 +69,8 @@ p.funcFormat    = 2;
 
 % path for tissue probability maps (in spm8/tpm) for 'new segment'
 p.TPMimg        = '$spm8_dir/toolbox/Seg/TPM.nii';
+
+p.REALIGN		= $REALIGN
 
 EOT
 echo "Parameters file $SAVE_DIR/p_DARTEL.m written and saved."
