wrote update_nii in funcs, added more comments throughout, echos to logfiles, updated so end of scripts say [LABEL] Done.

diff --git a/scripts/funcs b/scripts/funcs
--- a/scripts/funcs
+++ b/scripts/funcs
@@ -22,6 +22,7 @@ source globals.par
 ###########################################
 
 function num2subID {
+	label='[NUMSUB]'
 	unset SUBIDS
 	re_num='^[0-9]+$'
 
@@ -46,14 +47,11 @@ function num2subID {
 				SUBIDS[$i]=s00"${snums[$i]}"
 			fi
 		else
-			echo "Unrecognized subject ID format: ${snum}"
-			echo "Please enter in one of the following formats:"
-			echo "'1' such that the array looks like (1 2 5 9)."
+			echo "${label} Unrecognized subject ID format: ${snum}"
 			exit
 		fi
 		i=$i+1
 	done
-	echo "Subject list: ${SUBIDS[@]}"
 }
 
 ################################################################################
@@ -73,16 +71,17 @@ function num2subID {
 ###########################################
 
 function get_subs {
+	label='[GETSUB]'
 	set -e # stop immediately when an error occurs
 	unset SUBS
 	tsk=$1
 
 	if [[ $# -le 1 ]]; then
-		if [[ $# -eq 0 ]] && [[ ${NUM_TASKS} -gt 1 ]]; then echo "Please specify a task: ${TASKS[@]}. Aborting..."; exit; fi
+		if [[ $# -eq 0 ]] && [[ ${NUM_TASKS} -gt 1 ]]; then echo "${label} Must specify a task: ${TASKS[@]}. Aborting..."; exit; fi
 		if [[ $# -eq 0 ]]; then tsk=$TASKS; fi
 		# NEW SUBJECTS: no subject input means run all new subjects only, based on raw/
 		# make list of all subjects in raw/
-		if ! [[ -d ${RAW_DIR}/${tsk}/ ]]; then echo "'${tsk}' is not a valid task name. Aborting..."; exit; fi
+		if ! [[ -d ${RAW_DIR}/${tsk}/ ]]; then echo "${label} '${tsk}' is not a valid task name. Aborting..."; exit; fi
 		i=0
 		for s in $(ls -d ${RAW_DIR}/${tsk}/*/ | xargs -n 1 basename); do
 			subs_all[$i]=$s;
@@ -115,7 +114,7 @@ function get_subs {
 			fi
 		done
 		# SUBS now contains an array of new subjects that have not been preprocessed
-		echo "No subjects given.  Selecting all ${#SUBS[@]} new subjects for task $tsk: ${SUBS[@]}"
+		echo "${label} No subjects given.  Selecting all ${#SUBS[@]} new subjects for task $tsk: ${SUBS[@]}"
 	elif [[ $2 == 'all' ]]; then
 		# ALL SUBJECTS: run all subjects in task, even those who have already been preprocessed
 		i=0
@@ -123,23 +122,23 @@ function get_subs {
 			SUBS[$i]=$s
 			i=$i+1
 		done
-		echo "Selecting all ${#SUBS[@]} subjects for task ${tsk}: ${SUBS[@]}"
+		echo "${label} Selecting all ${#SUBS[@]} subjects for task ${tsk}: ${SUBS[@]}"
 	else
 		# RUN SELECT SUBJECTS: run only the subjects inputted
 		declare -a subs=("${!2}")
 		# convert subject numbers to form (s000)
 		num2subID subs[@]
 		i=0
+		# make sure inputted subjects are already converted and in raw
 		for s in "${SUBIDS[@]}"; do
 			for p in $(ls -d ${RAW_DIR}/${tsk}/*/ | xargs -n 1 basename); do
 				if [[ $s == $p ]]; then
-					# found folder with same name as subject.  Delete from list
 					SUBS[$i]=$s;
 					i=$i+1
 				fi
 			done
 		done
-		echo "Selecting all ${#SUBS[@]} inputted subjects for task $tsk: ${SUBS[@]}"
+		echo "${label} Selecting all ${#SUBS[@]} inputted subjects for task $tsk: ${SUBS[@]}"
 	fi
 }
 
@@ -173,20 +172,50 @@ EOT
 # 4)
 # wait_for_it
 # author Miriam Weaverdyck, August 22, 2016
-# This function waits until log file contains "[INPUT] Done."
+# This function waits until logfile contains "[STEP_LABEL] Done."
+###########################################
+# Arguments (2 total):
+#  step_label 	: the label written in the logfile (must be all caps in logfile)
+#  logfile		: the logfile to search in
 ###########################################
 
 function wait_for_it {
-	if [[ $# -eq 0 ]]; then echo "[WAIT] Please specify a step to search for. Aborting..."; exit; fi
+	label='[WAIT]'
+	if [[ ! $# -eq 2 ]]; then 
+		echo "${label} Please specify a step_label to search for and a logfile to search in. Aborting..."; exit; 
+	fi
 
-	step=${1^^}
+	step_label=${1^^}
 	logfile=$2
 	SLEEP_INTERVAL=10   # this is in seconds
 
-	while [ -z "$(grep [$step] Done. $logfile)" ]; do
+	while [ -z "$(grep [${step_label}] Done. $logfile)" ]; do
 		# still running...
 		sleep $SLEEP_INTERVAL
 	done
 
-	echo "[WAIT] $step finished (based on logfile $logfile). Moving on..."
+	echo "${label} ${step_label} finished (based on logfile $logfile). Moving on..."
 }
+
+################################################################################
+# 5)
+# update_nii
+# author Miriam Weaverdyck, August 23, 2016
+# This function updates niftis to their most recently modified formats
+###########################################
+
+function update_nii {
+	# count number of original epi_r##.nii files there are
+	num_runs="$(find ./ -type f -name 'epi_r*.nii' | wc -l)";
+	# go through and store each of those filenames in runs
+	for ((i=1; i<=${num_runs}; i++)); do runs[$i]="$(find ./ -type f -name 'epi_r*.nii' | head -$i | tail -1 | xargs -n 1 basename)"; done
+	# go through runs and find the most recent version (with prefixes) then update original file to most recent version
+	for r in "${runs[@]}"; do cp "$(find *${r} -type f -printf '%T@ %p\n' | sort -rn | head -n 1 | cut -f2- -d" ")" "$r"; done
+	# go through all other files (in orig_nii) and update those to their most recent versions
+	orig_nii=("anat.nii" "epi_SE_AP.nii" "epi_SE_PA.nii");
+	for n in "${orig_nii[@]}"; do cp "$(find *${n} -type f -printf '%T@ %p\n' | sort -rn | head -n 1 | cut -f2- -d" ")" "$n"; done
+}
+
+
+
+
